# Form implementation generated from reading ui file 'presentation/screens/AuthWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(800, 600)
        AuthWindow.setMinimumSize(QtCore.QSize(800, 600))
        AuthWindow.setMaximumSize(QtCore.QSize(900, 600))
        AuthWindow.setStyleSheet("/* ===== Fondo general ===== */\n"
"QDialog#AuthWindow {\n"
"  background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #0b1210, stop:1 #0f1c17);\n"
"  color: #E8EEF7;\n"
"  font-family: \"Segoe UI\", \"Inter\", Arial;\n"
"}\n"
"\n"
"/* ===== Tarjeta ===== */\n"
"QFrame#cardLogin {\n"
"  background: #ffffff;\n"
"  border: 1px solid #d1d5db;\n"
"  border-radius: 14px;\n"
"  padding: 24px;\n"
"  max-width: 420px;\n"
"}\n"
"\n"
"/* ===== Título ===== */\n"
"QLabel#lblTitleLogin {\n"
"  color: #0b3d2e;\n"
"  font-size: 30px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .5px;\n"
"  border: none;\n"
"}\n"
"\n"
"/* ===== Labels ===== */\n"
"QLabel#lblUser, QLabel#lblPwd {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtUsuario, QLineEdit#txtPassword {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtUsuario:focus, QLineEdit#txtPassword:focus {\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtUsuario::placeholder, QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}\n"
"\n"
"/* ===== Botón principal (Login) ===== */\n"
"QPushButton#btnLogin {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnLogin:hover   { background: #17b455; }\n"
"QPushButton#btnLogin:pressed { background: #12803e; }\n"
"QPushButton#btnLogin:disabled{\n"
"  background: #a7f3d0; color: #065f46; border-color: #86efac;\n"
"}\n"
"\n"
"/* ===== Botón secundario (Registro) ===== */\n"
"QPushButton#btnRegister {\n"
"  background: transparent;\n"
"  color: #0b3d2e;\n"
"  border: 1px solid #94a3b8;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnRegister:hover {\n"
"  border-color: #16a34a;\n"
"  color: #065f46;\n"
"}\n"
"/* ===== Tarjeta ===== */\n"
"QFrame#cardRegister {\n"
"  background: #ffffff;\n"
"  border: 1px solid #d1d5db;\n"
"  border-radius: 14px;\n"
"  padding: 24px;\n"
"  max-width: 420px;\n"
"}\n"
"\n"
"/* ===== Título ===== */\n"
"QLabel#lblTitleRegister {\n"
"  color: #0b3d2e;\n"
"  font-size: 30px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .5px;\n"
"  border: none;\n"
"}\n"
"\n"
"/* ===== Labels ===== */\n"
"QLabel#lblPwd1, QLabel#lblPwd2, QLabel#lblUserR {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtUserRegister, QLineEdit#txtPwdRegister, QLineEdit#txtPwdValidate {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtUserRegister:focus, QLineEdit#txtPwdRegister:focus, QLineEdit#txtPwdValidate:focus {\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtUserRegister::placeholder, QLineEdit#txtPwdRegister::placeholder,QLineEdit#txtPwdValidate::placeholder {\n"
"  color: #94a3b8;\n"
"}\n"
"\n"
"/* ===== Botón principal (Register) ===== */\n"
"QPushButton#btnRegisterR {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnLoginR:hover   { background: #17b455; }\n"
"QPushButton#btnLoginR:pressed { background: #12803e; }\n"
"QPushButton#btnLoginR:disabled{\n"
"  background: #a7f3d0; color: #065f46; border-color: #86efac;\n"
"}\n"
"\n"
"/* ===== Botón secundario (Login) ===== */\n"
"QPushButton#btnLoginR {\n"
"  background: transparent;\n"
"  color: #0b3d2e;\n"
"  border: 1px solid #94a3b8;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnRegisterR:hover {\n"
"  border-color: #16a34a;\n"
"  color: #065f46;\n"
"}\n"
"\n"
"")
        self.stackAuth = QtWidgets.QStackedWidget(parent=AuthWindow)
        self.stackAuth.setGeometry(QtCore.QRect(219, 100, 361, 400))
        self.stackAuth.setMinimumSize(QtCore.QSize(361, 400))
        self.stackAuth.setMaximumSize(QtCore.QSize(16777215, 400))
        self.stackAuth.setObjectName("stackAuth")
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setObjectName("pageLogin")
        self.cardLogin = QtWidgets.QFrame(parent=self.pageLogin)
        self.cardLogin.setGeometry(QtCore.QRect(0, 0, 361, 400))
        self.cardLogin.setMinimumSize(QtCore.QSize(100, 100))
        self.cardLogin.setMaximumSize(QtCore.QSize(470, 16777215))
        self.cardLogin.setBaseSize(QtCore.QSize(100, 100))
        self.cardLogin.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardLogin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardLogin.setObjectName("cardLogin")
        self.gridLayout = QtWidgets.QGridLayout(self.cardLogin)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(24, 24, 24, 24)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitleLogin = QtWidgets.QLabel(parent=self.cardLogin)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblTitleLogin.setFont(font)
        self.lblTitleLogin.setStyleSheet("")
        self.lblTitleLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleLogin.setObjectName("lblTitleLogin")
        self.gridLayout.addWidget(self.lblTitleLogin, 0, 0, 1, 2)
        self.lblUser = QtWidgets.QLabel(parent=self.cardLogin)
        self.lblUser.setObjectName("lblUser")
        self.gridLayout.addWidget(self.lblUser, 1, 0, 1, 1)
        self.txtUsuario = QtWidgets.QLineEdit(parent=self.cardLogin)
        self.txtUsuario.setEnabled(True)
        self.txtUsuario.setMinimumSize(QtCore.QSize(0, 30))
        self.txtUsuario.setObjectName("txtUsuario")
        self.gridLayout.addWidget(self.txtUsuario, 1, 1, 1, 1)
        self.lblPwd = QtWidgets.QLabel(parent=self.cardLogin)
        self.lblPwd.setStyleSheet("")
        self.lblPwd.setObjectName("lblPwd")
        self.gridLayout.addWidget(self.lblPwd, 2, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.cardLogin)
        self.txtPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPassword.setStyleSheet("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 2, 1, 1, 1)
        self.btnRegister = QtWidgets.QPushButton(parent=self.cardLogin)
        self.btnRegister.setObjectName("btnRegister")
        self.gridLayout.addWidget(self.btnRegister, 3, 0, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(parent=self.cardLogin)
        self.btnLogin.setStyleSheet("")
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout.addWidget(self.btnLogin, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.stackAuth.addWidget(self.pageLogin)
        self.pageRegister = QtWidgets.QWidget()
        self.pageRegister.setObjectName("pageRegister")
        self.cardRegister = QtWidgets.QFrame(parent=self.pageRegister)
        self.cardRegister.setGeometry(QtCore.QRect(0, 0, 361, 400))
        self.cardRegister.setMinimumSize(QtCore.QSize(100, 100))
        self.cardRegister.setMaximumSize(QtCore.QSize(470, 16777215))
        self.cardRegister.setBaseSize(QtCore.QSize(100, 100))
        self.cardRegister.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardRegister.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardRegister.setObjectName("cardRegister")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cardRegister)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(24, 24, 24, 24)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnRegisterR = QtWidgets.QPushButton(parent=self.cardRegister)
        self.btnRegisterR.setStyleSheet("")
        self.btnRegisterR.setObjectName("btnRegisterR")
        self.gridLayout_2.addWidget(self.btnRegisterR, 4, 1, 1, 1)
        self.txtPwdRegister = QtWidgets.QLineEdit(parent=self.cardRegister)
        self.txtPwdRegister.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPwdRegister.setStyleSheet("")
        self.txtPwdRegister.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.txtPwdRegister.setObjectName("txtPwdRegister")
        self.gridLayout_2.addWidget(self.txtPwdRegister, 2, 1, 1, 1)
        self.lblPwd1 = QtWidgets.QLabel(parent=self.cardRegister)
        self.lblPwd1.setStyleSheet("")
        self.lblPwd1.setObjectName("lblPwd1")
        self.gridLayout_2.addWidget(self.lblPwd1, 2, 0, 1, 1)
        self.txtUserRegister = QtWidgets.QLineEdit(parent=self.cardRegister)
        self.txtUserRegister.setEnabled(True)
        self.txtUserRegister.setMinimumSize(QtCore.QSize(0, 30))
        self.txtUserRegister.setObjectName("txtUserRegister")
        self.gridLayout_2.addWidget(self.txtUserRegister, 1, 1, 1, 1)
        self.btnLoginR = QtWidgets.QPushButton(parent=self.cardRegister)
        self.btnLoginR.setObjectName("btnLoginR")
        self.gridLayout_2.addWidget(self.btnLoginR, 4, 0, 1, 1)
        self.lblUserR = QtWidgets.QLabel(parent=self.cardRegister)
        self.lblUserR.setObjectName("lblUserR")
        self.gridLayout_2.addWidget(self.lblUserR, 1, 0, 1, 1)
        self.lblTitleRegister = QtWidgets.QLabel(parent=self.cardRegister)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblTitleRegister.setFont(font)
        self.lblTitleRegister.setStyleSheet("")
        self.lblTitleRegister.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleRegister.setObjectName("lblTitleRegister")
        self.gridLayout_2.addWidget(self.lblTitleRegister, 0, 0, 1, 2)
        self.lblPwd2 = QtWidgets.QLabel(parent=self.cardRegister)
        self.lblPwd2.setObjectName("lblPwd2")
        self.gridLayout_2.addWidget(self.lblPwd2, 3, 0, 1, 1)
        self.txtPwdValidate = QtWidgets.QLineEdit(parent=self.cardRegister)
        self.txtPwdValidate.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPwdValidate.setStyleSheet("")
        self.txtPwdValidate.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.txtPwdValidate.setObjectName("txtPwdValidate")
        self.gridLayout_2.addWidget(self.txtPwdValidate, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.stackAuth.addWidget(self.pageRegister)

        self.retranslateUi(AuthWindow)
        self.stackAuth.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Dialog"))
        self.lblTitleLogin.setText(_translate("AuthWindow", "INICIAR SESION"))
        self.lblUser.setText(_translate("AuthWindow", "Usuario"))
        self.lblPwd.setText(_translate("AuthWindow", "Contraseña"))
        self.btnRegister.setText(_translate("AuthWindow", "Registrarse"))
        self.btnLogin.setText(_translate("AuthWindow", "Iniciar Sesion"))
        self.btnRegisterR.setText(_translate("AuthWindow", "Registrarse"))
        self.lblPwd1.setText(_translate("AuthWindow", "Contraseña"))
        self.btnLoginR.setText(_translate("AuthWindow", "Iniciar Sesion"))
        self.lblUserR.setText(_translate("AuthWindow", "Usuario"))
        self.lblTitleRegister.setText(_translate("AuthWindow", "REGISTRO"))
        self.lblPwd2.setText(_translate("AuthWindow", "Repetir Contraseña"))
