# Form implementation generated from reading ui file 'presentation/screens/LoginPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(800, 600)
        LoginPage.setMinimumSize(QtCore.QSize(800, 600))
        LoginPage.setMaximumSize(QtCore.QSize(800, 600))
        LoginPage.setStyleSheet("/* ===== Fondo general ===== */\n"
"QWidget#LoginPage {\n"
"  background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #0b1210, stop:1 #0f1c17);\n"
"  color: #E8EEF7;\n"
"  font-family: \"Segoe UI\", \"Inter\", Arial;\n"
"}\n"
"\n"
"/* ===== Tarjeta ===== */\n"
"QFrame#cardLogin {\n"
"  background: #ffffff;\n"
"  border: 1px solid #d1d5db;\n"
"  border-radius: 14px;\n"
"  padding: 24px;\n"
"  max-width: 420px;\n"
"}\n"
"\n"
"/* ===== Título ===== */\n"
"QLabel#lblTitleLogin {\n"
"  color: #0b3d2e;\n"
"  font-size: 30px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .5px;\n"
"  border: none;\n"
"}\n"
"\n"
"/* ===== Labels ===== */\n"
"QLabel#lblUser, QLabel#lblPwd {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtUsuario, QLineEdit#txtPassword {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtUsuario:focus, QLineEdit#txtPassword:focus {\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtUsuario::placeholder, QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}\n"
"\n"
"/* ===== Botón principal (Login) ===== */\n"
"QPushButton#btnLogin {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnLogin:hover   { background: #17b455; }\n"
"QPushButton#btnLogin:pressed { background: #12803e; }\n"
"QPushButton#btnLogin:disabled{\n"
"  background: #a7f3d0; color: #065f46; border-color: #86efac;\n"
"}\n"
"\n"
"/* ===== Botón secundario (Registro) ===== */\n"
"QPushButton#btnRegister {\n"
"  background: transparent;\n"
"  color: #0b3d2e;\n"
"  border: 1px solid #94a3b8;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnRegister:hover {\n"
"  border-color: #16a34a;\n"
"  color: #065f46;\n"
"}\n"
"")
        self.cardLogin = QtWidgets.QFrame(parent=LoginPage)
        self.cardLogin.setGeometry(QtCore.QRect(210, 90, 361, 400))
        self.cardLogin.setMinimumSize(QtCore.QSize(100, 100))
        self.cardLogin.setMaximumSize(QtCore.QSize(470, 16777215))
        self.cardLogin.setBaseSize(QtCore.QSize(100, 100))
        self.cardLogin.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardLogin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardLogin.setObjectName("cardLogin")
        self.gridLayout = QtWidgets.QGridLayout(self.cardLogin)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(24, 24, 24, 24)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitleLogin = QtWidgets.QLabel(parent=self.cardLogin)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblTitleLogin.setFont(font)
        self.lblTitleLogin.setStyleSheet("")
        self.lblTitleLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleLogin.setObjectName("lblTitleLogin")
        self.gridLayout.addWidget(self.lblTitleLogin, 0, 0, 1, 2)
        self.lblUser = QtWidgets.QLabel(parent=self.cardLogin)
        self.lblUser.setObjectName("lblUser")
        self.gridLayout.addWidget(self.lblUser, 1, 0, 1, 1)
        self.txtUsuario = QtWidgets.QLineEdit(parent=self.cardLogin)
        self.txtUsuario.setEnabled(True)
        self.txtUsuario.setMinimumSize(QtCore.QSize(0, 30))
        self.txtUsuario.setObjectName("txtUsuario")
        self.gridLayout.addWidget(self.txtUsuario, 1, 1, 1, 1)
        self.lblPwd = QtWidgets.QLabel(parent=self.cardLogin)
        self.lblPwd.setStyleSheet("")
        self.lblPwd.setObjectName("lblPwd")
        self.gridLayout.addWidget(self.lblPwd, 2, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.cardLogin)
        self.txtPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPassword.setStyleSheet("")
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 2, 1, 1, 1)
        self.btnRegister = QtWidgets.QPushButton(parent=self.cardLogin)
        self.btnRegister.setObjectName("btnRegister")
        self.gridLayout.addWidget(self.btnRegister, 3, 0, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(parent=self.cardLogin)
        self.btnLogin.setStyleSheet("")
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout.addWidget(self.btnLogin, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Form"))
        self.lblTitleLogin.setText(_translate("LoginPage", "INICIAR SESION"))
        self.lblUser.setText(_translate("LoginPage", "Usuario"))
        self.lblPwd.setText(_translate("LoginPage", "Contraseña"))
        self.btnRegister.setText(_translate("LoginPage", "Registrarse"))
        self.btnLogin.setText(_translate("LoginPage", "Iniciar Sesion"))
