# Form implementation generated from reading ui file 'presentation/screens/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("/* ===== Fondo general ===== */\n"
"QMainWindow#MainWindow,\n"
"QWidget#centralwidget {\n"
"  background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #0b1210, stop:1 #0f1c17);\n"
"  color: #E8EEF7;\n"
"  font-family: \"Segoe UI\",\"Inter\",Arial;\n"
"}\n"
"\n"
"QStackedWidget#stackMain {\n"
"  background: #ffffff;\n"
"  border: 1px solid #ffffff;\n"
"  border-radius: 10px;\n"
"}\n"
"\n"
"/* ===== Título superior (bienvenida) ===== */\n"
"QLabel#lblWelcomeUser {\n"
"  color: #ffffff;\n"
"  font-size: 22px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .3px;\n"
"  border: none;\n"
"  padding: 4px 0 8px 0;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   TÍTULOS DE SECCIÓN (todas las páginas)\n"
"   ======================================================= */\n"
"QLabel#lblTituloCrearCuentas_3,\n"
"QLabel#lblTituloComprarMoneda,\n"
"QLabel#lblTituloVenderMoneda,\n"
"QLabel#lblTituloDepositarMoneda {\n"
"  color: #0f172a;\n"
"  font-size: 26px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .3px;\n"
"  border: none;\n"
"  padding: 4px 0 8px 0;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   LABELS DE CAMPO (todas las páginas)\n"
"   ======================================================= */\n"
"QLabel#lblMoneda_3,\n"
"QLabel#lblCantidadCompra,\n"
"QLabel#lblMonedaCompra,\n"
"QLabel#lblMonedaVender,\n"
"QLabel#lblCantidadVender,\n"
"QLabel#lblCantidadDeposito {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   BOTONES PRINCIPALES \"VERDES\"\n"
"   (se agrupan y se mantiene override para btnCerrar:disabled)\n"
"   ======================================================= */\n"
"QPushButton#btnCerrar,\n"
"QPushButton#btnCreateAccount_3,\n"
"QPushButton#btnPurchase,\n"
"QPushButton#btnSell,\n"
"QPushButton#btnDeposit {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnCerrar:hover,\n"
"QPushButton#btnCreateAccount_3:hover,\n"
"QPushButton#btnPurchase:hover,\n"
"QPushButton#btnSell:hover,\n"
"QPushButton#btnDeposit:hover   { background: #17b455; }\n"
"\n"
"QPushButton#btnCerrar:pressed,\n"
"QPushButton#btnCreateAccount_3:pressed,\n"
"QPushButton#btnPurchase:pressed,\n"
"QPushButton#btnSell:pressed,\n"
"QPushButton#btnDeposit:pressed { background: #12803e; }\n"
"\n"
"/* disabled general para los verdes (paginas); luego override para btnCerrar */\n"
"QPushButton#btnCreateAccount_3:disabled,\n"
"QPushButton#btnPurchase:disabled,\n"
"QPushButton#btnSell:disabled,\n"
"QPushButton#btnDeposit:disabled {\n"
"  background: #e5f7ed;\n"
"  color: #065f46;\n"
"  border-color: #bfead3;\n"
"}\n"
"/* override: btnCerrar conserva su disabled original diferente */\n"
"QPushButton#btnCerrar:disabled {\n"
"  background: #a7f3d0;\n"
"  color: #065f46;\n"
"  border-color: #86efac;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   BOTONES SECUNDARIOS (menú)\n"
"   ======================================================= */\n"
"QPushButton#btnCreateAccountM,\n"
"QPushButton#btnDepositM,\n"
"QPushButton#btnPurchaseM,\n"
"QPushButton#btnSellM {\n"
"  background: #ffffff;\n"
"  color: #0b3d2e;\n"
"  border: 1px solid #94a3b8;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnCreateAccountM:hover,\n"
"QPushButton#btnDepositM:hover,\n"
"QPushButton#btnPurchaseM:hover,\n"
"QPushButton#btnSellM:hover {\n"
"  background: #16a34a;\n"
"  border-color: #ffffff;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   COMBOBOX (todas las páginas)\n"
"   ======================================================= */\n"
"QComboBox#cmbCurrency_3,\n"
"QComboBox#cmbPurchaseCurrency,\n"
"QComboBox#cmbSellCurrency {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 8px 36px 8px 10px;  /* espacio para flecha */\n"
"  min-height: 34px;\n"
"}\n"
"QComboBox#cmbCurrency_3:focus,\n"
"QComboBox#cmbPurchaseCurrency:focus,\n"
"QComboBox#cmbSellCurrency:focus {\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QComboBox#cmbCurrency_3::drop-down,\n"
"QComboBox#cmbPurchaseCurrency::drop-down,\n"
"QComboBox#cmbSellCurrency::drop-down {\n"
"  border: 0; width: 24px;\n"
"}\n"
"QComboBox#cmbCurrency_3 QAbstractItemView,\n"
"QComboBox#cmbPurchaseCurrency QAbstractItemView,\n"
"QComboBox#cmbSellCurrency QAbstractItemView {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  selection-background-color: #22c55e;\n"
"  selection-color: #ffffff;\n"
"  outline: 0;\n"
"}\n"
"\n"
"/* =========================================================\n"
"   LINE EDITS (todas las páginas)\n"
"   ======================================================= */\n"
"QLineEdit#txtPurchaseAmount,\n"
"QLineEdit#txtSellAmount,\n"
"QLineEdit#txtAmount {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtPurchaseAmount:focus,\n"
"QLineEdit#txtSellAmount:focus,\n"
"QLineEdit#txtAmount:focus {\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtPurchaseAmount::placeholder,\n"
"QLineEdit#txtSellAmount::placeholder,\n"
"QLineEdit#txtAmount::placeholder,\n"
"QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackMain = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackMain.setGeometry(QtCore.QRect(50, 140, 700, 400))
        self.stackMain.setMinimumSize(QtCore.QSize(700, 400))
        self.stackMain.setMaximumSize(QtCore.QSize(700, 400))
        self.stackMain.setObjectName("stackMain")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(parent=self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 691, 400))
        self.frame.setMaximumSize(QtCore.QSize(700, 400))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblMoneda_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblMoneda_3.setFont(font)
        self.lblMoneda_3.setObjectName("lblMoneda_3")
        self.gridLayout_3.addWidget(self.lblMoneda_3, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.lblTituloCrearCuentas_3 = QtWidgets.QLabel(parent=self.frame)
        self.lblTituloCrearCuentas_3.setObjectName("lblTituloCrearCuentas_3")
        self.gridLayout_3.addWidget(self.lblTituloCrearCuentas_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        self.btnCreateAccount_3 = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.btnCreateAccount_3.setFont(font)
        self.btnCreateAccount_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreateAccount_3.setObjectName("btnCreateAccount_3")
        self.gridLayout_3.addWidget(self.btnCreateAccount_3, 4, 2, 1, 1)
        self.cmbCurrency_3 = QtWidgets.QComboBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCurrency_3.sizePolicy().hasHeightForWidth())
        self.cmbCurrency_3.setSizePolicy(sizePolicy)
        self.cmbCurrency_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cmbCurrency_3.setObjectName("cmbCurrency_3")
        self.cmbCurrency_3.addItem("")
        self.cmbCurrency_3.addItem("")
        self.gridLayout_3.addWidget(self.cmbCurrency_3, 2, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 2)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.stackMain.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ComprarMonedaFrame = QtWidgets.QFrame(parent=self.frame_2)
        self.ComprarMonedaFrame.setGeometry(QtCore.QRect(0, 0, 691, 400))
        self.ComprarMonedaFrame.setMaximumSize(QtCore.QSize(700, 400))
        self.ComprarMonedaFrame.setStyleSheet("/* ==== Título ==== */\n"
"QLabel#lblTituloComprarMoneda {\n"
"  color: #0f172a;\n"
"  font-size: 26px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .3px;\n"
"  border: none;\n"
"  padding: 4px 0 8px 0;\n"
"}\n"
"\n"
"/* ==== Label de campo ==== */\n"
"QLabel#lblCantidadCompra,QLabel#lblMonedaCompra  {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ==== ComboBox (dropdown) ==== */\n"
"QComboBox#cmbCurrencyCompra {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 8px 36px 8px 10px;  \n"
"  min-height: 34px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra:focus {\n"
"  border: 2px solid #22c55e;     /* acento verde */\n"
"  background: #ffffff;\n"
"}\n"
"QComboBox#cmbCurrencyCompra::drop-down {\n"
"  border: 0; width: 24px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra QAbstractItemView {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  selection-background-color: #22c55e;\n"
"  selection-color: #ffffff;\n"
"  outline: 0;\n"
"}\n"
"\n"
"/* ==== Botón principal ==== */\n"
"QPushButton#btnComprarMoneda {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnComprarMoneda:hover   { background: #17b455; }\n"
"QPushButton#btnComprarMoneda:pressed { background: #12803e; }\n"
"QPushButton#btnComprarMoneda:disabled{\n"
"  background: #e5f7ed; color: #065f46; border-color: #bfead3;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtCantidadCompra {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtCantidadCompra:focus{\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtCantidadCompra::placeholder, QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}")
        self.ComprarMonedaFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ComprarMonedaFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ComprarMonedaFrame.setObjectName("ComprarMonedaFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ComprarMonedaFrame)
        self.gridLayout_4.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_4.setSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 6, 1, 1, 1)
        self.btnPurchase = QtWidgets.QPushButton(parent=self.ComprarMonedaFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.btnPurchase.setFont(font)
        self.btnPurchase.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPurchase.setObjectName("btnPurchase")
        self.gridLayout_4.addWidget(self.btnPurchase, 5, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 1, 1, 1, 1)
        self.cmbPurchaseCurrency = QtWidgets.QComboBox(parent=self.ComprarMonedaFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPurchaseCurrency.sizePolicy().hasHeightForWidth())
        self.cmbPurchaseCurrency.setSizePolicy(sizePolicy)
        self.cmbPurchaseCurrency.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cmbPurchaseCurrency.setObjectName("cmbPurchaseCurrency")
        self.cmbPurchaseCurrency.addItem("")
        self.cmbPurchaseCurrency.addItem("")
        self.gridLayout_4.addWidget(self.cmbPurchaseCurrency, 2, 2, 1, 1)
        self.lblMonedaCompra = QtWidgets.QLabel(parent=self.ComprarMonedaFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblMonedaCompra.setFont(font)
        self.lblMonedaCompra.setObjectName("lblMonedaCompra")
        self.gridLayout_4.addWidget(self.lblMonedaCompra, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem5, 4, 2, 1, 1)
        self.lblTituloComprarMoneda = QtWidgets.QLabel(parent=self.ComprarMonedaFrame)
        self.lblTituloComprarMoneda.setObjectName("lblTituloComprarMoneda")
        self.gridLayout_4.addWidget(self.lblTituloComprarMoneda, 0, 0, 1, 1)
        self.lblCantidadCompra = QtWidgets.QLabel(parent=self.ComprarMonedaFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblCantidadCompra.setFont(font)
        self.lblCantidadCompra.setObjectName("lblCantidadCompra")
        self.gridLayout_4.addWidget(self.lblCantidadCompra, 3, 1, 1, 1)
        self.txtPurchaseAmount = QtWidgets.QLineEdit(parent=self.ComprarMonedaFrame)
        self.txtPurchaseAmount.setObjectName("txtPurchaseAmount")
        self.gridLayout_4.addWidget(self.txtPurchaseAmount, 3, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.gridLayout_4.setColumnStretch(2, 2)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.stackMain.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.ComprarMonedaFrame_2 = QtWidgets.QFrame(parent=self.page_3)
        self.ComprarMonedaFrame_2.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.ComprarMonedaFrame_2.setMaximumSize(QtCore.QSize(700, 400))
        self.ComprarMonedaFrame_2.setStyleSheet("/* ==== Título ==== */\n"
"QLabel#lblTituloComprarMoneda {\n"
"  color: #0f172a;\n"
"  font-size: 26px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .3px;\n"
"  border: none;\n"
"  padding: 4px 0 8px 0;\n"
"}\n"
"\n"
"/* ==== Label de campo ==== */\n"
"QLabel#lblCantidadCompra,QLabel#lblMonedaCompra  {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ==== ComboBox (dropdown) ==== */\n"
"QComboBox#cmbCurrencyCompra {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 8px 36px 8px 10px;  \n"
"  min-height: 34px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra:focus {\n"
"  border: 2px solid #22c55e;     /* acento verde */\n"
"  background: #ffffff;\n"
"}\n"
"QComboBox#cmbCurrencyCompra::drop-down {\n"
"  border: 0; width: 24px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra QAbstractItemView {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  selection-background-color: #22c55e;\n"
"  selection-color: #ffffff;\n"
"  outline: 0;\n"
"}\n"
"\n"
"/* ==== Botón principal ==== */\n"
"QPushButton#btnComprarMoneda {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnComprarMoneda:hover   { background: #17b455; }\n"
"QPushButton#btnComprarMoneda:pressed { background: #12803e; }\n"
"QPushButton#btnComprarMoneda:disabled{\n"
"  background: #e5f7ed; color: #065f46; border-color: #bfead3;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtCantidadCompra {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtCantidadCompra:focus{\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtCantidadCompra::placeholder, QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}")
        self.ComprarMonedaFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ComprarMonedaFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ComprarMonedaFrame_2.setObjectName("ComprarMonedaFrame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ComprarMonedaFrame_2)
        self.gridLayout_5.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_5.setSpacing(12)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 6, 1, 1, 1)
        self.btnSell = QtWidgets.QPushButton(parent=self.ComprarMonedaFrame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.btnSell.setFont(font)
        self.btnSell.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSell.setObjectName("btnSell")
        self.gridLayout_5.addWidget(self.btnSell, 5, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_5.addItem(spacerItem7, 1, 1, 1, 1)
        self.cmbSellCurrency = QtWidgets.QComboBox(parent=self.ComprarMonedaFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSellCurrency.sizePolicy().hasHeightForWidth())
        self.cmbSellCurrency.setSizePolicy(sizePolicy)
        self.cmbSellCurrency.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cmbSellCurrency.setObjectName("cmbSellCurrency")
        self.cmbSellCurrency.addItem("")
        self.cmbSellCurrency.addItem("")
        self.gridLayout_5.addWidget(self.cmbSellCurrency, 2, 2, 1, 1)
        self.lblMonedaVender = QtWidgets.QLabel(parent=self.ComprarMonedaFrame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblMonedaVender.setFont(font)
        self.lblMonedaVender.setObjectName("lblMonedaVender")
        self.gridLayout_5.addWidget(self.lblMonedaVender, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 4, 2, 1, 1)
        self.lblTituloVenderMoneda = QtWidgets.QLabel(parent=self.ComprarMonedaFrame_2)
        self.lblTituloVenderMoneda.setObjectName("lblTituloVenderMoneda")
        self.gridLayout_5.addWidget(self.lblTituloVenderMoneda, 0, 0, 1, 1)
        self.lblCantidadVender = QtWidgets.QLabel(parent=self.ComprarMonedaFrame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblCantidadVender.setFont(font)
        self.lblCantidadVender.setObjectName("lblCantidadVender")
        self.gridLayout_5.addWidget(self.lblCantidadVender, 3, 1, 1, 1)
        self.txtSellAmount = QtWidgets.QLineEdit(parent=self.ComprarMonedaFrame_2)
        self.txtSellAmount.setObjectName("txtSellAmount")
        self.gridLayout_5.addWidget(self.txtSellAmount, 3, 2, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 2)
        self.gridLayout_5.setColumnStretch(2, 2)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_5.setRowStretch(2, 1)
        self.stackMain.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.ComprarMonedaFrame_3 = QtWidgets.QFrame(parent=self.page_4)
        self.ComprarMonedaFrame_3.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.ComprarMonedaFrame_3.setMaximumSize(QtCore.QSize(700, 400))
        self.ComprarMonedaFrame_3.setStyleSheet("/* ==== Título ==== */\n"
"QLabel#lblTituloComprarMoneda {\n"
"  color: #0f172a;\n"
"  font-size: 26px;\n"
"  font-weight: 800;\n"
"  letter-spacing: .3px;\n"
"  border: none;\n"
"  padding: 4px 0 8px 0;\n"
"}\n"
"\n"
"/* ==== Label de campo ==== */\n"
"QLabel#lblCantidadCompra,QLabel#lblMonedaCompra  {\n"
"  color: #334155;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"/* ==== ComboBox (dropdown) ==== */\n"
"QComboBox#cmbCurrencyCompra {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 8px 36px 8px 10px;  \n"
"  min-height: 34px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra:focus {\n"
"  border: 2px solid #22c55e;     /* acento verde */\n"
"  background: #ffffff;\n"
"}\n"
"QComboBox#cmbCurrencyCompra::drop-down {\n"
"  border: 0; width: 24px;\n"
"}\n"
"QComboBox#cmbCurrencyCompra QAbstractItemView {\n"
"  background: #ffffff;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  selection-background-color: #22c55e;\n"
"  selection-color: #ffffff;\n"
"  outline: 0;\n"
"}\n"
"\n"
"/* ==== Botón principal ==== */\n"
"QPushButton#btnComprarMoneda {\n"
"  background: #16a34a;\n"
"  color: #ffffff;\n"
"  border: 1px solid #15803d;\n"
"  border-radius: 10px;\n"
"  padding: 10px 16px;\n"
"  font-weight: 600;\n"
"}\n"
"QPushButton#btnComprarMoneda:hover   { background: #17b455; }\n"
"QPushButton#btnComprarMoneda:pressed { background: #12803e; }\n"
"QPushButton#btnComprarMoneda:disabled{\n"
"  background: #e5f7ed; color: #065f46; border-color: #bfead3;\n"
"}\n"
"\n"
"/* ===== Campos ===== */\n"
"QLineEdit#txtCantidadCompra {\n"
"  background: #f8fafc;\n"
"  color: #111827;\n"
"  border: 1px solid #cbd5e1;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"QLineEdit#txtCantidadCompra:focus{\n"
"  border: 2px solid #22c55e;\n"
"  background: #ffffff;\n"
"}\n"
"QLineEdit#txtCantidadCompra::placeholder, QLineEdit#txtPassword::placeholder {\n"
"  color: #94a3b8;\n"
"}")
        self.ComprarMonedaFrame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ComprarMonedaFrame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ComprarMonedaFrame_3.setObjectName("ComprarMonedaFrame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ComprarMonedaFrame_3)
        self.gridLayout_6.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_6.setSpacing(12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblCantidadDeposito = QtWidgets.QLabel(parent=self.ComprarMonedaFrame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.lblCantidadDeposito.setFont(font)
        self.lblCantidadDeposito.setObjectName("lblCantidadDeposito")
        self.gridLayout_6.addWidget(self.lblCantidadDeposito, 2, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 5, 2, 1, 1)
        self.btnDeposit = QtWidgets.QPushButton(parent=self.ComprarMonedaFrame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        self.btnDeposit.setFont(font)
        self.btnDeposit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDeposit.setObjectName("btnDeposit")
        self.gridLayout_6.addWidget(self.btnDeposit, 4, 3, 1, 1)
        self.lblTituloDepositarMoneda = QtWidgets.QLabel(parent=self.ComprarMonedaFrame_3)
        self.lblTituloDepositarMoneda.setObjectName("lblTituloDepositarMoneda")
        self.gridLayout_6.addWidget(self.lblTituloDepositarMoneda, 0, 0, 1, 1)
        self.txtAmount = QtWidgets.QLineEdit(parent=self.ComprarMonedaFrame_3)
        self.txtAmount.setObjectName("txtAmount")
        self.gridLayout_6.addWidget(self.txtAmount, 2, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem10, 3, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 0, 1, 1, 1)
        self.stackMain.addWidget(self.page_4)
        self.btnCerrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(670, 20, 101, 41))
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCerrar.setObjectName("btnCerrar")
        self.btnCreateAccountM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCreateAccountM.setGeometry(QtCore.QRect(50, 90, 130, 40))
        self.btnCreateAccountM.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreateAccountM.setObjectName("btnCreateAccountM")
        self.btnPurchaseM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchaseM.setGeometry(QtCore.QRect(210, 90, 130, 40))
        self.btnPurchaseM.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPurchaseM.setObjectName("btnPurchaseM")
        self.btnSellM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSellM.setGeometry(QtCore.QRect(370, 90, 130, 40))
        self.btnSellM.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSellM.setObjectName("btnSellM")
        self.btnDepositM = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDepositM.setGeometry(QtCore.QRect(530, 90, 130, 40))
        self.btnDepositM.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDepositM.setObjectName("btnDepositM")
        self.lblWelcomeUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblWelcomeUser.setGeometry(QtCore.QRect(50, 10, 254, 47))
        self.lblWelcomeUser.setText("")
        self.lblWelcomeUser.setObjectName("lblWelcomeUser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblMoneda_3.setText(_translate("MainWindow", "Ingrese la moneda"))
        self.lblTituloCrearCuentas_3.setText(_translate("MainWindow", "Crear cuenta nueva"))
        self.btnCreateAccount_3.setText(_translate("MainWindow", "Crear cuenta"))
        self.cmbCurrency_3.setItemText(0, _translate("MainWindow", "ARS"))
        self.cmbCurrency_3.setItemText(1, _translate("MainWindow", "USD"))
        self.btnPurchase.setText(_translate("MainWindow", "Comprar"))
        self.cmbPurchaseCurrency.setItemText(0, _translate("MainWindow", "ARS"))
        self.cmbPurchaseCurrency.setItemText(1, _translate("MainWindow", "USD"))
        self.lblMonedaCompra.setText(_translate("MainWindow", "Ingrese la moneda"))
        self.lblTituloComprarMoneda.setText(_translate("MainWindow", "Comprar moneda"))
        self.lblCantidadCompra.setText(_translate("MainWindow", "Cantidad"))
        self.btnSell.setText(_translate("MainWindow", "Vender"))
        self.cmbSellCurrency.setItemText(0, _translate("MainWindow", "ARS"))
        self.cmbSellCurrency.setItemText(1, _translate("MainWindow", "USD"))
        self.lblMonedaVender.setText(_translate("MainWindow", "Ingrese la moneda"))
        self.lblTituloVenderMoneda.setText(_translate("MainWindow", "Vender moneda"))
        self.lblCantidadVender.setText(_translate("MainWindow", "Cantidad"))
        self.lblCantidadDeposito.setText(_translate("MainWindow", "Cantidad"))
        self.btnDeposit.setText(_translate("MainWindow", "Vender"))
        self.lblTituloDepositarMoneda.setText(_translate("MainWindow", "Depositar"))
        self.btnCerrar.setText(_translate("MainWindow", "Cerrar Sesión"))
        self.btnCreateAccountM.setText(_translate("MainWindow", "Crear cuenta"))
        self.btnPurchaseM.setText(_translate("MainWindow", "Comprar moneda"))
        self.btnSellM.setText(_translate("MainWindow", "Vender moneda"))
        self.btnDepositM.setText(_translate("MainWindow", "Depositar ARS"))
